name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        type: string
        description: string
        required: true

jobs:
  release:
    if: github.triggering_actor == 'sinhashubham95'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
          stable: false

      - name: Cleanup dependencies
        run: go mod tidy

      - name: Create tag
        run: |
          git config --global user.name '${{ github.triggering_actor }}'
          git config --global user.email "${{ github.triggering_actor}}@users.noreply.github.com"
          git add .
          git commit -m 'bump ${{ inputs.semver }}'
          git tag ${{ inputs.semver }}
          git push origin ${{ inputs.semver }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ inputs.semver }}
          tag_name: ${{ inputs.semver }}
