name: Tests

on:
  push:
    tags:
    branches:
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x ]
        platform: [ ubuntu-latest ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: true

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test
        run: make coverage

      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
          flags: unittests
          verbose: true
