name: Tests

on:
  push:
    tags:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.18.x, 1.19.x, 1.20.x, 1.21.x ]
        platform: [ ubuntu-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
          stable: true

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Test
        run: make coverage

      - name: Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./cover.out
          flags: unittests
          verbose: true
